# NXProject Processor 3.1.0 Image

FROM mcr.microsoft.com/dotnet/core/runtime:3.1

RUN apt install libc6
RUN apt-get update
RUN apt-get install -y libgif-dev autoconf libtool automake build-essential gettext libglib2.0-dev libcairo2-dev libtiff-dev libexif-dev
RUN apt-get install -y libgdiplus
