#!/bin/bash

# /certs -- location where keys are stored
# $ACCOUNT_EMAIL -- email to associate with these registrations
# $DOMAIN -- domain to retrieve certificate for

if [ ! -d /certs ]
then
    echo "/certs is not a valid directory" >&2
    exit 1
fi

if [ ! $ACCOUNT_EMAIL ]
then
    echo "ACCOUNT_EMAIL must be set" >&2
    exit 1
fi

if [ ! $DOMAIN ]
then
    echo "DOMAIN must be set" >&2
    exit 1
fi

if [ "$DRY_RUN" == "true" ]
    export EXTRA_ARGS="--dry-run $EXTRA_ARGS"
fi


certbot_run () {
    exec certbot certonly $EXTRA_ARGS \
        --email $ACCOUNT_EMAIL --non-interactive --agree-tos \
        --expand \
        --config-dir /certs \
        --standalone -d "$DOMAIN"
}

if [ -f /certs/synch.flag ]
then
    if [ -f /certs/live/$DOMAIN/fullchain.pem ]
    then
        if [ "$(date %d)" = "20" ]
        then
            certbot_run
        fi
    else
        certbot_run
    fi
fi
