#!/bin/bash
if [ ! -d /certs ]
then
    echo "/certs is not a valid directory" >&2
    exit 1
fi

if [ ! $ACCOUNT_EMAIL ]
then
    echo "ACCOUNT_EMAIL must be set" >&2
    exit 1
fi

if [ ! $DOMAIN ]
then
    echo "DOMAIN must be set" >&2
    exit 1
fi

if [ -f /certs/synch.flag ]
then
    if [ ! -f /certs/live/$DOMAIN/fullchain.pem ]
    then
        bash /run/renew-all
    fi
fi

if [ "$RUN_ONCE" = "true" ]
then
    exec /run/renew-all
else
    cp /run/crontab /etc/cron.d/crontab
    exec cron -f -L 0
fi