#!/bin/bash
certbotsc_start() {
    echo $(date --utc -Ins) > /certbotsc.pid
}
certbotsc_exit() {
    rm /certbotsc.pid
}
certbotsc_lastrun() {
    echo $(date --utc -I) > /certbotsc.lr
}

if [ ! -d /certs ]
then
    echo "/certs is not a valid directory" >> /etc/nxp/renew.log
    exit 1
fi

if [ ! $ACCOUNT_EMAIL ]
then
    echo "ACCOUNT_EMAIL must be set"  >> /etc/nxp/renew.log
    echo ":${ACCOUNT_EMAIL}:"  >> /etc/nxp/renew.log
    exit 1
fi

if [ ! $DOMAIN ]
then
    echo "DOMAIN must be set"  >> /etc/nxp/renew.log
    exit 1
fi

if [ "$DRY_RUN" = "true" ]
then
    export EXTRA_ARGS="--dry-run $EXTRA_ARGS"
fi

certbot_run () {
    certbot certonly $EXTRA_ARGS \
        --email $ACCOUNT_EMAIL --non-interactive --agree-tos \
        --expand \
        --config-dir /certs \
        --deploy-hook '/run/renew-all certdone' \
        --standalone -d "$DOMAIN"
}

if [ "${1}" = "certdone" ]
then
    certbotsc_lastrun
    rm /certs/synch.flag
    exit 0
fi

if [ ! -f /certbotsc.pid ]
then
    certbotsc_start
    if [ -f /certs/synch.flag ]
    then
        if [ -f /certs/live/$DOMAIN/fullchain.pem ]
        then
            if [ "$(date %d)" = "20" ]
            then
                if [ ! -f /certbotsc.lr || "$(cat /certbotsc.lr)" != "$(date --utc -I)" ]
                then
                    certbot_run
                fi
            fi
        else
            certbot_run
        fi
    fi
    certbotsc_exit
fi